version: '2'

services:
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    links:
      - server
  server:
    build: ./server
    restart: always
    ports:
      - "4443:4443"
    volumes:
      - ./server:/server

